def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any
    tools {
        maven "maven3"
        jdk "jdk8"
    }

    environment {
        cluster = "vproprod"
        service = "vproappprdsvc"

    }



    stages {
        stage('Depoly to ECS PRD') {
            steps{
                echo 'use withAWS to pass cred for jenkins to manage ecs'
                echo 'ecs service and task, ecs service will inform task to fetch latest image redeploy'
                echo 'this will delete old container and create new on based on latest image'
                echo 'use shell cmd to update-service, force deploy new image'
                withAWS(credentials: 'awscreds', region: 'ap-southeast-2') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }               

    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#cidi',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}
}


